services:
  hdland:
    image: ${DOCKER_REGISTRY-}hdland
    build:
      context: .
      dockerfile: HDLand/Dockerfile
    ports:
        - "8081:8081"
    container_name: hdland_webapi
    depends_on: 
        - hdland_db
  hdland_db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hdland
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: hdland_db
  hdland_frontend:  
    build:
      context: ./HDLandFront  
      dockerfile: Dockerfile  
    ports:
      - "5173:5173"  
    container_name: hdland_frontend
    depends_on:
      - hdland  
volumes:
    db_data:    