services:
  hdland:
    image: ${DOCKER_REGISTRY-}hdland
    build:
      context: .
      dockerfile: HDLand/Dockerfile
    ports:
        - "8080:8080"
    container_name: hdland_webapi
    depends_on: 
        - db
  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hdland
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: hdland_db

volumes:
    db_data:    